In [1]:
import torch
import pandas as pd

In [2]:
cd ..

/home/yann/IVISpaces


In [3]:
FBNN={'boston': {('FBNN', 'RMSE'): 2.378, ('FBNN', 'LPP'): -2.301},
      'concrete': {('FBNN', 'RMSE'): 4.935, ('FBNN', 'LPP'): -3.096},
      'energy': {('FBNN', 'RMSE'): 0.412, ('FBNN', 'LPP'): -0.684},
      'wine': {('FBNN', 'RMSE'): 0.673, ('FBNN', 'LPP'): -1.040},
      'yacht': {('FBNN', 'RMSE'): 0.607, ('FBNN', 'LPP'): -1.033}
     }
sFBNN={'boston': {('FBNN', 'RMSE'): 0.104, ('FBNN', 'LPP'): 0.038},
      'concrete': {('FBNN', 'RMSE'): 0.180, ('FBNN', 'LPP'): 0.016},
      'energy': {('FBNN', 'RMSE'): 0.017, ('FBNN', 'LPP'): 0.020},
      'wine': {('FBNN', 'RMSE'): 0.014, ('FBNN', 'LPP'): 0.013},
      'yacht': {('FBNN', 'RMSE'): 0.068, ('FBNN', 'LPP'): 0.033}
     }

In [7]:
RESULTS=torch.load('Results/NEW/UCI2020-10-06-21:20.pt')

for dataset in RESULTS.keys():
    RESULTS[dataset].update(FBNN[dataset])
   # RESULTS[dataset].update(RESULTS_[dataset])

In [8]:
from itertools import product
methods=['MFVI','GeNNeVI','FuNNeVI','FuNNeVI-GP','FBNN']#['FuNNeVI','FuNNeVI-GP']
metrics=['RMSE','LPP']


# Defining custom function  
# which returns the list for 
# df.style.apply() method 
def boldface_min(s):  
    is_min = s == s.min()       
    return ['font-weight: bold' if cell else '' for cell in is_min] 
def boldface_max(s):  
    is_max = s == s.max()       
    return ['font-weight: bold' if cell else '' for cell in is_max] 



index=pd.MultiIndex.from_product([methods,metrics])#, names=['method', 'metric']
df=pd.DataFrame(data=RESULTS).transpose()
df[index].style.\
    apply(boldface_min,subset=[(method,'RMSE') for method in methods], axis=1).\
    apply(boldface_max,subset=[(method,'LPP') for method in methods], axis=1)

In [9]:
methods=['MFVI','GeNNeVI','FuNNeVI','FuNNeVI-GP']#['MFVI','GeNNeVI','FuNNeVI']
metrics=['std noise']
index=pd.MultiIndex.from_product([methods,metrics])

df[index]

MFVI   GeNNeVI   FuNNeVI FuNNeVI-GP
         std noise std noise std noise  std noise
boston    0.250530  0.148914  0.098045   0.068350
concrete  0.265197  0.171109  0.169347   0.151521
energy    0.047168  0.036712  0.040762   0.025594
wine      0.761143  0.520156  0.526737   0.490270
yacht     0.018708  0.019630  0.043126   0.018289

In [124]:
methods=['FuNNeVI','FuNNeVI-GP']#['MFVI','GeNNeVI','FuNNeVI']
metrics=['PICP','MPIW']
index=pd.MultiIndex.from_product([methods,metrics])

df[index]

FuNNeVI            FuNNeVI-GP          
              PICP       MPIW       PICP      MPIW
boston    0.862745   7.294689   0.294118  2.662351
concrete  0.786408   9.693829   0.786408  9.961894
energy    0.922078   1.432573   0.896104  1.145752
wine      0.893750   2.070171   0.825000  1.658202
yacht     1.000000  78.171082   0.709677  1.151614

In [58]:
from itertools import product
methods=['MFVI','GeNNeVI','FuNNeVI']
metrics=['RMSE','LPP']
index=pd.MultiIndex.from_product([methods,metrics])

df[index]

MFVI             GeNNeVI             FuNNeVI          
              RMSE       LPP      RMSE       LPP      RMSE       LPP
boston    2.250311 -2.210260  2.470490 -2.376171  2.983753 -2.452071
concrete  5.119310 -3.053566  4.424112 -3.013688  6.588360 -2.825999
energy    0.441243 -0.609612  0.379960 -0.434500  0.365694 -0.437678
wine      0.607687 -0.920256  0.678240 -1.335707  0.631621 -0.959469
yacht     1.090453 -3.771850  0.574238 -0.371805  0.673957 -0.687404

In [75]:
methods=['MFVI','GeNNeVI','FuNNeVI']
metrics=['std noise']
index=pd.MultiIndex.from_product([methods,metrics])

df[index]

MFVI   GeNNeVI   FuNNeVI
         std noise std noise std noise
boston    0.240262  0.161290  0.181519
concrete  0.287803  0.180094  0.177915
energy    0.042255  0.035391  0.036137
wine      0.765187  0.490276  0.506622
yacht     0.021039  0.022076  0.157405

In [34]:
methods=['MFVI','GeNNeVI','FuNNeVI']
metrics=['PICP','MPIW']
index=pd.MultiIndex.from_product([methods,metrics])

df[index]

MFVI              GeNNeVI              FuNNeVI           
                PICP       MPIW      PICP       MPIW      PICP       MPIW
boston      0.980392   8.753042  0.901961   6.262235  0.607843   6.415531
concrete    0.932039  18.736496  0.854369  11.826075  0.805825  10.579023
energy      0.909091   1.718983  0.935065   1.479000  0.844156   1.169286
powerplant  0.965517  16.006853  0.959248  15.137009  0.961338  15.111128
wine        0.943750   2.357448  0.825000   1.769144  0.750000   1.519049
yacht       0.903226   1.908560  0.903226   1.474181  0.870968   1.389844

In [5]:
pd.DataFrame(data=RESULTS).transpose()

FuNNeVI                                                          \
                RMSE       LPP         WAIC      PICP       MPIW    time [s]   
boston      3.499170 -9.706475 -5033.416436  0.411765   3.490517   58.667553   
concrete    4.716959 -0.551132    -0.562228  0.815534  10.887134   85.777502   
energy      0.418305  1.723983     1.708440  0.909091   1.377645   62.911350   
powerplant  3.686524  0.111957     0.111581  0.956113  15.227015  526.151184   
wine        0.699910 -2.075601    -2.081987  0.743750   1.381247  199.641761   
yacht       0.692175  0.982335     0.518029  0.903226   1.309118   32.205426   

             GeNNeVI                                                       
                RMSE       LPP      WAIC      PICP       MPIW    time [s]  
boston      2.467883 -0.260145 -1.653744  0.862745   6.209254   55.124422  
concrete    4.390738 -0.224997 -0.738069  0.834951  11.492492  109.351131  
energy      0.365739  1.899910  1.547915  0.948052   1.455620   84.581293  
powerplant  3.663045  0.116750  0.110883  0.957158  15.285971  677.902806  
wine        0.687988 -1.533913 -1.889386  0.787500   1.690457  275.106008  
yacht       0.573080  2.201985 -1.444338  0.935484   1.512225   35.752383

In [65]:
pd.DataFrame(data=RESULTS).transpose()

FuNNeVI                                                          \
                RMSE       LPP         WAIC      PICP       MPIW    time [s]   
boston      3.410029 -4.065264 -7236.635576  0.588235   6.305422  100.204100   
concrete    4.705148 -0.535952  -194.918032  0.815534  12.591081  169.540660   
energy      0.474275  1.595990     1.567385  0.883117   1.550657  126.602165   
powerplant  3.655491  0.119665     0.106125  0.959248  15.203786  991.791639   
wine        0.818962 -2.318930    -2.469340  0.737500   1.540062  401.863890   
yacht       0.749524  1.019889   -17.449427  0.870968   1.527083   51.101782   

             GeNNeVI                                                       
                RMSE       LPP      WAIC      PICP       MPIW    time [s]  
boston      2.344702 -0.105311 -0.997385  0.843137   6.478037   55.259652  
concrete    4.739773 -0.284358 -0.655225  0.834951  12.757685  102.308992  
energy      0.390879  1.846950  1.318433  0.935065   1.441588   92.562668  
powerplant  3.663800  0.117330  0.107851  0.960293  15.155389  779.957575  
wine        0.721144 -1.788957 -2.105563  0.781250   1.587880  296.848780  
yacht       0.491450  2.174269 -0.300490  0.903226   1.604549   31.518639

In [46]:
RESULTS=torch.load('Results/NEW/FuNoise2020-10-01-17:19.pt')

RESULTS_={}
for i in RESULTS:
    for dataset in i.keys():
        metrics= list(i[dataset].keys())
        for j in metrics:
            i[dataset][('FuNNeVI',j)] = i[dataset].pop(j)
    RESULTS_.update(i)

In [47]:
pd.DataFrame(data=RESULTS_).transpose()

FuNNeVI                                                        
                RMSE       LPP         WAIC      PICP       MPIW    time [s]
boston      3.283971 -1.873660 -2347.286502  0.745098   6.479837   43.316867
concrete    5.261525 -0.625764    -0.661693  0.864078  12.402017   85.345163
energy      0.385033  1.770556     1.711370  0.883117   1.172862   74.896005
powerplant  3.646586  0.122132    -4.400473  0.965517  15.185143  486.080443
wine        0.699884 -1.656919    -1.668136  0.812500   1.640723  129.821529
yacht       1.088323  1.178053     1.138152  0.935484   3.335503   26.053682

In [58]:
RESULTS_GeN=torch.load('Results/NEW/GeNoise2020-10-01-19:08.pt')

RESULTS_G={}
for i in RESULTS_GeN:
    for dataset in i.keys():
        metrics= list(i[dataset].keys())
        for j in metrics:
            i[dataset][('GeNNeVI',j)] = i[dataset].pop(j)

    RESULTS_[dataset].update(i[dataset])

In [59]:
df=pd.DataFrame(data=RESULTS_).transpose()
df[[('GeNNeVI','RMSE'),('GeNNeVI','LPP'),('FuNNeVI','RMSE'),('FuNNeVI','LPP')]]

GeNNeVI             FuNNeVI          
                RMSE       LPP      RMSE       LPP
boston      2.343591 -0.038041  3.283971 -1.873660
concrete    5.172817 -0.302844  5.261525 -0.625764
energy      0.368241  1.900519  0.385033  1.770556
powerplant  3.634457  0.124018  3.646586  0.122132
wine        0.675931 -1.424935  0.699884 -1.656919
yacht       0.727912  1.822367  1.088323  1.178053

In [27]:
RESULTS_

[{'boston': {('FuNNeVI', 'RMSE'): 3.283970594406128,
   ('FuNNeVI', 'LPP'): -1.8736597299575806,
   ('FuNNeVI', 'WAIC'): -2347.2865015268326,
   ('FuNNeVI', 'PICP'): 0.7450980544090271,
   ('FuNNeVI', 'MPIW'): 6.479836940765381,
   ('FuNNeVI', 'time [s]'): 43.31686661299318}},
 {'concrete': {('FuNNeVI', 'RMSE'): 5.261524677276611,
   ('FuNNeVI', 'LPP'): -0.6257640719413757,
   ('FuNNeVI', 'WAIC'): -0.6616934351623058,
   ('FuNNeVI', 'PICP'): 0.8640776872634888,
   ('FuNNeVI', 'MPIW'): 12.402016639709473,
   ('FuNNeVI', 'time [s]'): 85.34516256535426}},
 {'energy': {('FuNNeVI', 'RMSE'): 0.3850327730178833,
   ('FuNNeVI', 'LPP'): 1.7705556154251099,
   ('FuNNeVI', 'WAIC'): 1.711369838565588,
   ('FuNNeVI', 'PICP'): 0.8831169009208679,
   ('FuNNeVI', 'MPIW'): 1.1728618144989014,
   ('FuNNeVI', 'time [s]'): 74.89600473735482}},
 {'powerplant': {('FuNNeVI', 'RMSE'): 3.6465864181518555,
   ('FuNNeVI', 'LPP'): 0.12213189154863358,
   ('FuNNeVI', 'WAIC'): -4.400472573935986,
   ('FuNNeVI', 'PI

# Results on Splits #

In [4]:
RESULTS, STDS=torch.load('Results/NEW/UCI_splits2020-10-06-23:35.pt')
RESULTS_data, _=torch.load('Results/NEW/UCI_splits2020-10-07-12:17.pt')



In [5]:
for dataset in RESULTS.keys():
    RESULTS[dataset].update(FBNN[dataset])
    RESULTS[dataset].update(RESULTS_data[dataset])

for dataset in STDS.keys():
    STDS[dataset].update(sFBNN[dataset])

In [6]:
res=pd.DataFrame(RESULTS).transpose().round(3)

In [7]:
stds=pd.DataFrame(STDS).transpose().round(3)

In [80]:
res

MFVI                                                         \
           RMSE    LPP   gLPP   WAIC   PICP    MPIW time [s] std noise   
boston    3.696 -2.969 -3.135 -4.721  0.884   9.386  115.577     0.239   
concrete  5.425 -3.121 -3.126 -3.249  0.921  19.321  226.411     0.285   
energy    0.460 -0.666 -0.660 -0.802  0.930   1.842  191.096     0.044   
wine        NaN    NaN    NaN    NaN    NaN     NaN      NaN       NaN   
yacht       NaN    NaN    NaN    NaN    NaN     NaN      NaN       NaN   

         GeNNeVI         ... FuNNeVI-GP                                  \
            RMSE    LPP  ...       RMSE     LPP    gLPP     WAIC   PICP   
boston     3.729 -4.342  ...      4.013 -18.454 -20.817 -100.612  0.388   
concrete   4.480 -3.165  ...      4.618  -3.475  -3.548   -3.692  0.829   
energy     0.452 -0.611  ...      0.461  -0.845  -0.963   -1.298  0.845   
wine         NaN    NaN  ...        NaN     NaN     NaN      NaN    NaN   
yacht        NaN    NaN  ...        NaN     NaN     NaN      NaN    NaN   

                                      FBNN         
            MPIW time [s] std noise   RMSE    LPP  
boston     2.958  168.390     0.072  2.378 -2.301  
concrete  10.024  258.083     0.152  4.935 -3.096  
energy     1.184  232.482     0.030  0.412 -0.684  
wine         NaN      NaN       NaN  0.673 -1.040  
yacht        NaN      NaN       NaN  0.607 -1.033  

[5 rows x 34 columns]

In [8]:
methods=['MFVI','GeNNeVI','FuNNeVI','FuNNeVI-GP','FBNN']#['FuNNeVI','FuNNeVI-GP']##
metrics=['RMSE','LPP']
index=pd.MultiIndex.from_product([methods,metrics])#, names=['method', 'metric']


# Defining custom function  
# which returns the list for 
# df.style.apply() method 
def boldface_min(s):  
    is_min = s == s.min()       
    return ['font-weight: bold' if cell else '' for cell in is_min] 
def boldface_max(s):  
    is_max = s == s.max()       
    return ['font-weight: bold' if cell else '' for cell in is_max] 



final=res[index].style.\
    apply(boldface_min,subset=[(method,'RMSE') for method in methods], axis=1).\
    apply(boldface_max,subset=[(method,'LPP') for method in methods], axis=1)
final

In [42]:
methods=['MFVI','GeNNeVI','FuNNeVI','FuNNeVI-GP','FBNN']#['FuNNeVI','FuNNeVI-GP']##
metrics=['RMSE','LPP']
index=pd.MultiIndex.from_product([methods,metrics])#, names=['method', 'metric']


# Defining custom function  
# which returns the list for 
# df.style.apply() method 
def boldface_min(s):  
    is_min = s == s.min()       
    return ['font-weight: bold' if cell else '' for cell in is_min] 
def boldface_max(s):  
    is_max = s == s.max()       
    return ['font-weight: bold' if cell else '' for cell in is_max] 



final=res[index].style.\
    apply(boldface_min,subset=[(method,'RMSE') for method in methods], axis=1).\
    apply(boldface_max,subset=[(method,'LPP') for method in methods], axis=1)
final

In [31]:
methods=['MFVI','GeNNeVI','FuNNeVI','FuNNeVI-GP']#['FuNNeVI','FuNNeVI-GP']
metrics=['PICP','MPIW','std noise']#, 'time [s]']




index=pd.MultiIndex.from_product([methods,metrics])#, names=['method', 'metric']
res[index]

MFVI                   GeNNeVI                   FuNNeVI          \
           PICP    MPIW std noise    PICP    MPIW std noise    PICP    MPIW   
boston    0.884   9.386     0.239   0.749   5.948     0.143   0.494   5.755   
concrete  0.921  19.321     0.285   0.864  11.530     0.167   0.822  10.907   
energy    0.930   1.842     0.044   0.909   1.368     0.032   0.864   1.186   
wine      0.938   2.434     0.757   0.824   1.746     0.529   0.744   1.580   
yacht     0.777   1.222     0.018   0.855   1.469     0.020   0.794   1.632   

                   FuNNeVI-GP                    
         std noise       PICP    MPIW std noise  
boston       0.093      0.388   2.958     0.072  
concrete     0.164      0.829  10.024     0.152  
energy       0.030      0.845   1.184     0.030  
wine         0.473      0.797   1.590     0.494  
yacht        0.027      0.700   1.083     0.016

In [28]:
methods=['MFVI','GeNNeVI','FuNNeVI','FuNNeVI-GP','FBNN']#['FuNNeVI','FuNNeVI-GP']
metrics=['RMSE','LPP']
index=pd.MultiIndex.from_product([methods,metrics])#, names=['method', 'metric']


import numpy as np
for i in res[index].columns:
    res[i] = res[i].astype(str)+ "±" + ((stds[i]/np.sqrt(10)).round(3)).astype(str)+""

In [29]:
res[index]

MFVI                    GeNNeVI                    FuNNeVI  \
                 RMSE           LPP         RMSE           LPP         RMSE   
boston    3.696±0.386   -2.969±0.26  3.729±0.473  -4.342±0.967   4.33±0.379   
concrete  5.425±0.142  -3.121±0.031   4.48±0.163  -3.165±0.114  4.779±0.212   
energy     0.46±0.022  -0.666±0.052  0.452±0.043   -0.611±0.09   0.437±0.03   
wine      0.645±0.012   -0.981±0.02  0.721±0.022  -1.342±0.064   0.82±0.026   
yacht     0.791±0.075  -3.348±1.135  0.652±0.075  -0.976±0.177  0.863±0.089   

                          FuNNeVI-GP                        FBNN                
                    LPP         RMSE            LPP         RMSE           LPP  
boston    -10.631±1.951   4.013±0.41  -18.454±5.318  2.378±0.033  -2.301±0.012  
concrete   -3.463±0.165    4.618±0.2   -3.475±0.148  4.935±0.057  -3.096±0.005  
energy     -0.811±0.153  0.461±0.029   -0.845±0.118  0.412±0.005  -0.684±0.006  
wine        -2.167±0.15  0.691±0.021     -1.46±0.08  0.673±0.004   -1.04±0.004  
yacht      -2.056±0.358  0.914±0.089   -4.697±1.465  0.607±0.022   -1.033±0.01

In [23]:
#goal N x T x 1

T=2
nb_predictors=3
mean=torch.Tensor([[[0.],[1.]]])#torch.zeros(1,T,1)#1 x T x 1
epistemic=torch.Tensor([1.,2.])#torch.ones(T,1) #T x 1
noise =torch.Tensor([[[1.], [2.]], [[3.], [4.]],[[5.],[6.]]])#torch.ones(nb_predictors,T,1)
pred= mean +epistemic* noise # 1 x T x 1 + (T x 1)*(T x N x 1) = N x T x 1

print(mean, mean.shape)
print(epistemic)
print(noise, noise.shape)
pred

tensor([[[0.],
         [1.]]]) torch.Size([1, 2, 1])
tensor([1., 2.])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]],

        [[5.],
         [6.]]]) torch.Size([3, 2, 1])


tensor([[[ 1.,  2.],
         [ 3.,  5.]],

        [[ 3.,  6.],
         [ 5.,  9.]],

        [[ 5., 10.],
         [ 7., 13.]]])

In [26]:
pd.DataFrame(torch.load('Results/NEW/UCI2020-10-07-16:56.pt')).transpose()

Mc_Drop                                                     \
                RMSE       LPP      gLPP      WAIC      PICP       MPIW   
boston      2.309210 -2.244050 -2.273166 -2.665961  0.921569   8.216378   
concrete    4.826562 -3.010382 -2.998851 -3.245234  0.941748  19.794645   
energy      1.210176 -1.829278 -1.810897 -2.019173  0.987013   8.021935   
powerplant  3.736268 -2.761766 -2.761572 -2.812600  0.975967  17.254574   
wine        0.585109 -0.882422 -0.885162 -0.953525  0.950000   2.191507   
yacht       1.011318 -1.645011 -1.709540 -2.007733  1.000000   7.570971   

                                
            time [s] std noise  
boston      4.285576  0.206794  
concrete    3.755984  0.274954  
energy      4.065505  0.179759  
powerplant  4.115696  0.249969  
wine        4.044397  0.677326  
yacht       3.198714  0.118164