In [12]:
import numpy as np
import torch
import pandas as pd
import mlflow


In [13]:
dataset='protein'

In [14]:
data=pd.read_csv(dataset+'/CASP.csv')
data

RMSD        F1       F2       F3        F4            F5        F6  \
0      17.284  13558.30  4305.35  0.31754  162.1730  1.872791e+06  215.3590   
1       6.021   6191.96  1623.16  0.26213   53.3894  8.034467e+05   87.2024   
2       9.275   7725.98  1726.28  0.22343   67.2887  1.075648e+06   81.7913   
3      15.851   8424.58  2368.25  0.28111   67.8325  1.210472e+06  109.4390   
4       7.962   7460.84  1736.94  0.23280   52.4123  1.021020e+06   94.5234   
...       ...       ...      ...      ...       ...           ...       ...   
45725   3.762   8037.12  2777.68  0.34560   64.3390  1.105797e+06  112.7460   
45726   6.521   7978.76  2508.57  0.31440   75.8654  1.116725e+06  102.2770   
45727  10.356   7726.65  2489.58  0.32220   70.9903  1.076560e+06  103.6780   
45728   9.791   8878.93  3055.78  0.34416   94.0314  1.242266e+06  115.1950   
45729  18.827  12732.40  4444.36  0.34905  157.6300  1.788897e+06  229.4590   

            F7   F8       F9  
0      4287.87  102  27.0302  
1      3328.91   39  38.5468  
2      2981.04   29  38.8119  
3      3248.22   70  39.0651  
4      2814.42   41  39.9147  
...        ...  ...      ...  
45725  3384.21   84  36.8036  
45726  3974.52   54  36.0470  
45727  3290.46   46  37.4718  
45728  3421.79   41  35.6045  
45729  4626.85  141  29.8118  

[45730 rows x 10 columns]

In [15]:
y=data['RMSD'].to_numpy()
print(y.shape)
X=data[['F{}'.format(i) for i in range(1,10)]].to_numpy()
X.shape

(45730,)


(45730, 9)

In [16]:
data_=X,y
torch.save(data_, dataset + '/data.pt' )

In [51]:
data = np.genfromtxt(dataset+'/CASP.csv', delimiter=',')
data


array([[        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [1.72840e+01, 1.35583e+04, 4.30535e+03, ..., 4.28787e+03,
        1.02000e+02, 2.70302e+01],
       [6.02100e+00, 6.19196e+03, 1.62316e+03, ..., 3.32891e+03,
        3.90000e+01, 3.85468e+01],
       ...,
       [1.03560e+01, 7.72665e+03, 2.48958e+03, ..., 3.29046e+03,
        4.60000e+01, 3.74718e+01],
       [9.79100e+00, 8.87893e+03, 3.05578e+03, ..., 3.42179e+03,
        4.10000e+01, 3.56045e+01],
       [1.88270e+01, 1.27324e+04, 4.44436e+03, ..., 4.62685e+03,
        1.41000e+02, 2.98118e+01]])

In [40]:

    # Les targets sont à la fin. 
X = data[:, range(data.shape[1] - 2) ]
y1 = data[:, data.shape[1] - 2]
y2 = data[:, data.shape[1] - 1]
X.shape,y1.shape,y2.shape



((11934, 16), (11934,), (11934,))

torch.Size([11934, 18])

In [43]:
torch.cat([torch.as_tensor(X),torch.as_tensor(y1).unsqueeze(-1),torch.as_tensor(y2).unsqueeze(-1)],dim=1)==torch.as_tensor(data) 

tensor([[True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        ...,
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True]])

In [44]:
data=X,y1
torch.save(data, dataset + '/dataCompressor.pt' )

In [45]:
data=X,y2
torch.save(data, dataset + '/dataTurbine.pt' )

In [5]:
def load_data(txt):

#    data = np.loadtxt(txt + '/' + txt + '.txt')
    data = np.genfromtxt(txt + '/' + txt + '.txt', delimiter='')

    # Les targets sont à la fin. 
    X = data[:, range(data.shape[1] - 1) ]
    y = data[:, data.shape[1] - 1]
    
    # Les targets sont au début. 
#    X = data[:, 0:]
#    y = data[:, 0]
    data=X,y
    torch.save(data, txt + '/data.pt' )
    return data

X,y=load_data('energy')
X.shape, y.shape

((768, 8), (768,))

In [47]:
np.std(y1),np.mean(y1)

(0.014719601443879758, 0.975)

In [6]:
X[0], y[0]

(array([  0.98, 514.5 , 294.  , 110.25,   7.  ,   2.  ,   0.  ,   0.  ]),
 15.55)

In [5]:
data=torch.load('concrete/data.pt')

In [6]:
data

(array([[ 540. ,    0. ,    0. , ..., 1040. ,  676. ,   28. ],
        [ 540. ,    0. ,    0. , ..., 1055. ,  676. ,   28. ],
        [ 332.5,  142.5,    0. , ...,  932. ,  594. ,  270. ],
        ...,
        [ 148.5,  139.4,  108.6, ...,  892.4,  780. ,   28. ],
        [ 159.1,  186.7,    0. , ...,  989.6,  788.9,   28. ],
        [ 260.9,  100.5,   78.3, ...,  864.5,  761.5,   28. ]]),
 array([79.99, 61.89, 40.27, ..., 23.7 , 32.77, 32.4 ]))